package com.temporary.backend.util;

import java.io.IOException;
import java.util.Properties;

/**
 * These global system settings are read from the config.properties file, which is generated by the
 * gradle build script according to the settings in the config.groovy file. If you need new properties,
 * you must follow this procedure:
 *
 * 1. Add the property in config.groovy. Make sure you define it in all environments.
 * 2. Add new getter methods to this class.
 * 3. If the new property is confidential, add it to the removal list in getPublicProperties() below.
 *
 * Do not edit the config.properties file directly. It will be regenerated each time the build script runs.
 * If you need to edit a property, edit config.groovy.
 */
public class SystemSettings {
    public static SystemSettings instance = new SystemSettings();
    private Properties properties;

    private SystemSettings() {
        properties = new Properties();
        try {
            properties.load(SystemSettings.class.getResourceAsStream("/config.properties"));
        } catch (IOException e) {
            properties.setProperty("error", e.getMessage());
        }
    }

    public Properties getAllProperties() {
        return properties;
    }

    public Properties getPublicProperties() {
        Properties pub = new Properties();
        pub.putAll(this.properties);
//        pub.remove("client_secret");
        return pub;
    }

    public EnvironmentType getEnvironment() {
        try {
            String s = properties.getProperty("indicator");
            return EnvironmentType.valueOf(s);
        } catch (Exception e) {
            return null;
        }
    }

    public boolean isProduction() {
        return getEnvironment().equals(EnvironmentType.prod);

    }
}
